version: '3'
services:
    php:
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME:?err}-php
        volumes:
            - './app:/var/www/html'
            - '/home:/home'
            - '~/:/web'
            - '~/tese:/Test'
   
    nginx:
        image: nginx:latest
        network: host
        args:
            - 'CERTBOT_EMAIL:oasis.sybill@webshule.online'
        DOMAIN_LIST:'file.webshule.online,*.file.webshule.online'
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - '800:80'
            - '444:443'
        links:
            - php
        volumes:
            - './app:/var/www/html'
            - '/home:/home'
            - '~/:/web'
            - '~/tese:/Test'
            - './config/nginx:/etc/nginx/conf.d'
            - 'letsencrypt:/etc/letsencrypt'
        restart: unless-stopped
