version: '3.4'
services:
    php:
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME:?err}-php
        volumes:
            - './app:/var/www/html'
            - './data/files:/home'
            
    nginx:
        image: nginx:latest
        container_name: ${APP_NAME:?err}-nginx
        build:
            context: ./nginx
            network: host
            args:
                - 'CERTBOT_EMAIL=oasis.sybill@webshule.online'
                - 'DOMAIN_LIST=file.webshule.online'
        restart: always
        volumes:
            - './app:/var/www/html'
            - '/home:/home'
            - '~/:/web'
            - '~/tese:/Test'
            - './config/nginx:/etc/nginx/conf.d'
            - '/letsencrypt:/etc/letsencrypt:rw'
        ports:
            - '80:80'
            - '443:443'
        links:
            - 'php'
        restart: unless-stopped
