version: '3'
services:
    php:
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: ${APP_NAME:?err}-php
        volumes:
            - './app:/var/www/html'
   
    nginx:
        image: nginx:latest
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - '80:800'
            - '443:444'
        links:
            - php
        volumes:
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'
